{{- if .Values.ingress.kube-api-proxy.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kube-api-proxy.fullname" . }}-kube-api-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.kube-api-proxy.tls }}
    {{- if (empty .Values.ingress.kube-api-proxy.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.kube-api-proxy.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "kube-api-proxy.name" . }}-kube-api-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.kube-api-proxy.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.kube-api-proxy.path }}
            backend:
              serviceName: {{ template "kube-api-proxy.fullname" . }}-kube-api-proxy
              servicePort: http
  {{- if .Values.ingress.kube-api-proxy.tls }}
  tls:
    - secretName: {{ template "kube-api-proxy.kube-api-proxy-certificate" . }}
      hosts:
        - {{ .Values.ingress.kube-api-proxy.hostname }}
  {{- end }}
{{- end }}
